// Shared barrel — currently a minimal re-export surface for cross-cutting
// types added during the #615 environment picker work. Existing modules are
// still imported by direct file path elsewhere in the codebase; new shared
// surfaces that span backend + frontend should also re-export from here so
// the picker has one stable import path.

export {
  ACTOR_CREDENTIAL_AUDIENCES,
  ACTOR_CREDENTIAL_TYPES,
  DEFAULT_SCOPED_ACTOR_CREDENTIAL_MAX_TTL_MS,
  ScopedActorCredentialRegistry,
  ScopedActorCredentialRegistryError,
  createScopedActorCredentialAuditEntry,
  isScopedActorCredentialAudience,
  isScopedActorCredentialType,
  redactScopedActorCredentialForAudit,
  type CreateScopedActorCredentialAuditEntryInput,
  type IssueScopedActorCredentialInput,
  type IssuedScopedActorCredential,
  type RevokeScopedActorCredentialInput,
  type ScopedActorCredentialActor,
  type ScopedActorCredentialAudience,
  type ScopedActorCredentialAuditEvent,
  type ScopedActorCredentialIssuer,
  type ScopedActorCredentialMetadata,
  type ScopedActorCredentialRecord,
  type ScopedActorCredentialScope,
  type ScopedActorCredentialType,
  type ScopedActorCredentialValidationFailureReason,
  type ScopedActorCredentialValidationResult,
  type ScopedActorCredentialValidationScope,
  type ValidateScopedActorCredentialInput,
} from './scoped-actor-credentials.js';

export {
  ENVIRONMENT_DEGRADED_REASONS,
  ENVIRONMENT_FRESHNESS_VALUES,
  ENVIRONMENT_OPTION_SCHEMA_VERSION,
  hasBench,
  hasRepoInstance,
  isEnvironmentDegradedReason,
  isEnvironmentFreshness,
  isEnvironmentOption,
  type EnvironmentBenchSummary,
  type EnvironmentCwdMode,
  type EnvironmentDegradedReason,
  type EnvironmentDegradedReasonKind,
  type EnvironmentFreshness,
  type EnvironmentNodeSummary,
  type EnvironmentOption,
  type EnvironmentRepoInstanceSummary,
} from './environment-option.js';

export {
  normalizeRemoteUrl,
  resolveCanonicalRepoIdentity,
  type CanonicalRepoIdentityResolution,
  type NormalizedRemoteIdentity,
  type RemoteDescriptor,
  type RemoteProvider,
  type RepoIdentityWarning,
  type ResolvedRemoteIdentity,
} from './repo-identity.js';

export {
  aggregateRepoInventoryReports,
  isRepoInventoryReport,
  summarizeRepoIdentityGroups,
  type AggregatedRepoInventoryGroup,
  type AggregatedRepoInventoryResponse,
  type RepoIdentityGroup,
  type RepoIdentityGroupInstance,
  type RepoIdentityGroupsResponse,
  type RepoInventoryRepoInstance,
  type RepoInventoryReport,
  type RepoInventoryWorktreeInstance,
} from './repo-inventory.js';

export {
  pickDefaultEnvironment,
  type ActiveTabContext,
  type EnvironmentHistoryEntry,
  type PickDefaultEnvironmentError,
  type PickDefaultEnvironmentErrorReason,
  type PickDefaultEnvironmentInput,
  type PickDefaultEnvironmentOk,
  type PickDefaultEnvironmentOkReason,
  type PickDefaultEnvironmentResult,
} from './safe-defaults.js';

export {
  HANDOFF_CONFLICT_CODES,
  HANDOFF_REASON_CODES,
  HANDOFF_REQUIRED_GRANT_LEGS,
  HANDOFF_RUN_STATES,
  HANDOFF_SCHEMA_VERSION,
  HANDOFF_SOURCE_DISPOSITIONS,
  HANDOFF_TRANSFER_MODES,
  isHandoffConflictCode,
  isHandoffPlan,
  isHandoffReasonCode,
  isHandoffRequest,
  isHandoffRun,
  isHandoffRunState,
  isHandoffRunTransitionAllowed,
  isHandoffSnapshot,
  isHandoffSourceDisposition,
  type HandoffConflict,
  type HandoffConflictCode,
  type HandoffDestinationProposal,
  type HandoffDestinationRef,
  type HandoffDestinationWriteMode,
  type HandoffLaunchPreview,
  type HandoffPathEndpoint,
  type HandoffPathKind,
  type HandoffPathMapping,
  type HandoffPlan,
  type HandoffReasonCode,
  type HandoffRequest,
  type HandoffRequiredGrant,
  type HandoffRequiredGrantLeg,
  type HandoffRun,
  type HandoffRunState,
  type HandoffRunTransition,
  type HandoffRuntimeRequest,
  type HandoffSnapshot,
  type HandoffSnapshotArtifactRef,
  type HandoffSnapshotGroup,
  type HandoffSourceDisposition,
  type HandoffSourceRef,
  type HandoffTransferMode,
} from './handoff.js';

export {
  PIPELINE_HANDOFF_ARTIFACT_SCHEMA_VERSION,
  PIPELINE_HANDOFF_COMMAND_STATUSES,
  PIPELINE_HANDOFF_EVIDENCE_DISPOSITIONS,
  PIPELINE_HANDOFF_IMPLEMENTATION_DECISIONS,
  PIPELINE_HANDOFF_PRIVATE_KANBAN_MARKDOWN_TEMPLATE,
  PIPELINE_HANDOFF_PUBLIC_MARKDOWN_TEMPLATE,
  PIPELINE_HANDOFF_QA_VERDICTS,
  PIPELINE_HANDOFF_RELEASE_VERDICTS,
  PIPELINE_HANDOFF_REVIEW_VERDICTS,
  PIPELINE_HANDOFF_RISK_LEVELS,
  PIPELINE_HANDOFF_STAGES,
  isPipelineHandoffArtifact,
  isPipelineHandoffArtifactStale,
  renderPipelineHandoffMarkdown,
  sanitizePipelineHandoffArtifactForPublic,
  validatePipelineHandoffArtifact,
  validatePublicPipelineHandoffArtifact,
  type PipelineHandoffArtifact,
  type PipelineHandoffBaseRef,
  type PipelineHandoffBranchRef,
  type PipelineHandoffCommandEvidence,
  type PipelineHandoffCommandStatus,
  type PipelineHandoffEvidence,
  type PipelineHandoffEvidenceArtifactRef,
  type PipelineHandoffEvidenceDisposition,
  type PipelineHandoffHeadRef,
  type PipelineHandoffImplementationDecision,
  type PipelineHandoffImplementationStage,
  type PipelineHandoffPrRef,
  type PipelineHandoffQaStage,
  type PipelineHandoffQaVerdict,
  type PipelineHandoffReleaseStage,
  type PipelineHandoffReleaseVerdict,
  type PipelineHandoffRepoRef,
  type PipelineHandoffReviewStage,
  type PipelineHandoffReviewVerdict,
  type PipelineHandoffRiskLevel,
  type PipelineHandoffScope,
  type PipelineHandoffStage,
  type PipelineHandoffStageBase,
  type PipelineHandoffStageName,
  type PipelineHandoffValidationResult,
} from './pipeline-handoff-artifact.js';

export {
  detectHandoffDestinationConflicts,
  proposeHandoffDestination,
  resolveHandoffPathMappings,
  validateHandoffDestinationRoot,
  validateHandoffMirrorRoot,
  type HandoffDestinationAction,
  type HandoffDestinationConflictInput,
  type HandoffDestinationProposalInput,
  type HandoffMirrorRoot,
  type HandoffPathMappingInput,
  type HandoffPathMappingResult,
} from './handoff-destination.js';

export {
  RESUME_CONFIDENCES,
  RESUME_EXCLUDE_CLASSES,
  RESUME_MODES,
  RESUME_READINESS_SIGNAL_KINDS,
  RESUME_STATE_LOCATION_KINDS,
  generateHandoffBrief,
  isAgentResumeBundle,
  isAgentStateExportPlan,
  isHarnessDescriptor,
  isResumeConfidence,
  isResumeExcludeClass,
  isResumeInstruction,
  isResumeMode,
  isResumeVerification,
  type AgentResumeBundle,
  type AgentStateExportPlan,
  type DestinationReadinessSignal,
  type GenerateHandoffBriefInput,
  type HarnessDescriptor,
  type NativeResumeCommandMetadata,
  type ResumeArtifactSummary,
  type ResumeConfidence,
  type ResumeEndpointRef,
  type ResumeExcludeClass,
  type ResumeInstruction,
  type ResumeInstructionProviderFields,
  type ResumeManifestSummary,
  type ResumeMode,
  type ResumeReadinessSignalKind,
  type ResumeStateLocation,
  type ResumeStateLocationKind,
  type ResumeTaskRef,
  type ResumeVerification,
  type SafeExcludeMetadata,
} from './agent-continuation.js';
